version: '3'

services:

  postgres:
    image: postgres
    container_name: postgres-cont
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: changeme
      PGDATA: /data/postgres
    volumes:
      - /data/postgres:/data/postgres
    ports:
      - "5432:5432"

  rabbitmq:
    image: rabbitmq
    container_name: rabbitmq-cont
    ports:
      - "5672:5672"