
spring:
  application:
    name: discovery
  cloud:
    config:
      uri: http://localhost:8888
      fail-fast: true

---
server:
  port: ${PORT:8761}
spring:
  profiles: peer1
eureka:
  client:
#    serviceUrl:
#      defaultZone: ${eureka-service.uri.peer2}:8762/eureka/ # replication
    register-with-eureka: false

---
server:
    port: ${PORT:8762}
spring:
  profiles: peer2
eureka:
  client:
    serviceUrl:
      defaultZone: ${eureka-service.uri.peer1}:8761/eureka/