server:
  port: ${PORT:8761}

spring:
  application:
    name: service-discovery

#eureka:
#  client:
#    registerWithEureka: false
#    fetchRegistry: false
#    server:
#      waitTimeInMsWhenSyncEmpty: 0