server:
  port: 8888
spring:
  application:
    name: config-server
  cloud:
    config:
      server:
        git:
          uri: file:///${user.home}/IdeaProjects/micro-config

eureka:
  client:
    service-url:
      defaultZone: ${micro.eureka.uri:http://127.0.0.1:8761}/eureka/

management:
  security:
    enabled: false

---
spring:
  profiles: docker
  cloud:
    config:
      server:
        git:
          uri: file://var/config
