server:
  port: 8000

spring:
  application:
    name: client
  cloud:
    config:
      uri: ${micro.config.uri}
      fail-fast: true
    loadbalancer:
      retry:
        enabled: true # Enable spring retry for ribbon
  rabbitmq:
    host: ${bus-service.uri}

management:
  security:
    enabled: false

eureka:
  client:
    service-url:
      defaultZone: ${micro.eureka.uri:http://127.0.0.1:8761}/eureka/
    register-with-eureka: false # hide client application in DS store

ribbon:
  eureka:
    enabled: true
  OkToRetryOnAllOperations: true
  MaxAutoRetries: 1
  MaxAutoRetriesNextServer: 1
  ReadTimeout: 1000


hystrix:
  command:
    default:
      execution:
        isolation:
          thread:
            timeoutInMilliseconds: 10000
  metrics:
    enabled:

netflix:
  atlas:
    enabled: false
    uri: http://127.0.0.1:7101

logging:
  level:
    com:
      netflix: WARN